//
// Created by user on 12/21/18.
//

#ifndef SIMPLEREMOTEDESKTOP_SDL_CLIENT_OPENMAXDECODER_H
#define SIMPLEREMOTEDESKTOP_SDL_CLIENT_OPENMAXDECODER_H


class OpenMaxDecoder {
    OpenMaxDecoder();
    void run(;)
};


#endif //SIMPLEREMOTEDESKTOP_SDL_CLIENT_OPENMAXDECODER_H
